### PR TITLE
Convert use of Moose to Moo.

### PR DESCRIPTION
**Pull request by dstroma**
All existing tests pass, including the "expensive" ones.
No new tests added.

Added two packages:
  - WebService::Rackspace::CloudFiles::Moo::Types
    Offers Moo-compatible types to replace the Moose ones.
  - WebService::Rackspace::CloudFiles::DateTime
    An empty sublcass of DateTime.

### CODE REVIEW

**Comment by Htbaa** [comment]
Looks good. Are you willing to take over maintainership of this module? I haven't used it in ages and don't really have the time to work on it.

**Comment by dstroma** [comment]
I could. I haven't officially authored or maintained any CPAN modules but I guess there's a first time for everything.

**Comment by dstroma** [comment]
Data::Stream::Bulk requires Moose, so it is still loaded anyway, I have to do more work on this.

**Comment by Htbaa** [comment]
Sorry for not responding earlier, I've been pretty busy. I was just about to merge your pull request but since Data::Stream::Bulk is still requiring Moose it wouldn't make a difference.

**Comment by dstroma** [comment]
I added new commits which address the issue. Data::Stream::Bulk is no longer required.

However there is a problem that somehow I missed last time with Pod::Coverage. Due to the way Moo vs. Moose adds attributes to a class, Pod::Coverage now flags attributes as undocumented methods. Can we just remove the pod coverage test?

**Comment by Htbaa** [comment]
POD::Coverage doesn't complain to me, so I guess it should be all fine.

**Comment by Htbaa** [comment]
Ah, now it somehow did. Will look into it, but it's fine by me.

**Pull request merged**
